### ISSUE TITLE
[Meta] packages with source unavailable

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2494]
packages with source unavailable because upstream URL is dead or redirect to nothing or domain was sold:

- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/blackhash/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/packerid/PKGBUILD --> https://github.com/sooshie/packerid/ ?
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/shellcodecs/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/vncrack/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/metoscan/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/phoss/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/ike-scan/PKGBUILD
- [ ] https://github.com/BlackArch/blackarch/blob/master/packages/dnsmap/PKGBUILD

**Comment by noraj** [comment]
http://16s.us/blackhash/ is dead and I wasn't able to find another source

**Comment by noraj** [comment]
Same fpr https://github.com/BlackArch/blackarch/blob/master/packages/packerid/PKGBUILD

**Comment by noraj** [comment]
Yeah you're right http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.xz redirects to http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.xz which doesn't exists anymore.

**Comment by D3vil0p3r** [comment]
**packerid**: https://github.com/sooshie/packerid/ should be right.

**vncrack**:
* URL: `url='http://194.150.168.69/vncrack/'`
* Source: `source=("http://194.150.168.69/vncrack/vncrack_src-1.21.tar.gz")`

**ike-scan**:
* Source: `source=("https://github.com/royhills/ike-scan/archive/refs/tags/1.9.5.tar.gz")`

**dnsmap**:
*URL: `url='https://github.com/resurrecting-open-source-projects/dnsmap'`
* Source: `source=("git+https://github.com/resurrecting-open-source-projects/dnsmap.git")`

What about the other ones? Will they be removed from the repository?

**Comment by anunna** [comment]
Yes they will be removed, but currently we are holding off on any package removals until further notice.

**Comment by noraj** [comment]
You could add them with a comment on https://github.com/BlackArch/blackarch/blob/master/lists/broken

**Comment by D3vil0p3r** [comment]
blackhash: **[It seems to have already a working updated source]**
packerid: https://github.com/BlackArch/blackarch/pull/4319
shellcodecs: added to broken -> https://github.com/BlackArch/blackarch/pull/4323
vncrack: https://github.com/BlackArch/blackarch/pull/4320
metoscan: added to broken -> https://github.com/BlackArch/blackarch/pull/4324
phoss: https://github.com/BlackArch/blackarch/pull/4322
ike-scan: **[It seems to have already a working updated source but build fails]**
dnsmap: https://github.com/BlackArch/blackarch/pull/4321

Feel free to update checkboxes on the 1st post

**Comment by D3vil0p3r** [comment]
Submitted fix for `ike-scan`. Once merged, this issue can be closed
